# pnpm-workspace.yaml
packages:
    - "packages/image-comparison-core"
    - "packages/visual-service"
    - "packages/ocr-service"
    - "packages/visual-reporter"
    - "packages/visual-remix-reporter"
