export const DEFAULT_IMAGES_FOLDER = '.tmp/'
export const SUPPORTED_LANGUAGES = {
    AFRIKAANS: 'afr',
    AMHARIC: 'amh',
    ARABIC: 'ara',
    ASSANESE: 'asm',
    AZERBAIJANI: 'aze',
    BELARUSIAN: 'bel',
    BENGALI: 'bel',
    TIBETAN: 'bod',
    BOSNIAN: 'bos',
    BULGARIAN: 'bul',
    CATALAN: 'cat',
    CZECH: 'cat',
    CHINESE: 'chi_sim',
    CORSICAN: 'cos',
    DANISH: 'dan',
    GERMAN: 'deu',
    GREEK: 'ell',
    ENGLISH: 'eng',
    MATH: 'equ',
    ESTONIAN: 'est',
    FINNISH: 'fin',
    FRENCH: 'fra',
    GAELIC: 'gla',
    IRISH: 'gle',
    HINDI: 'hin',
    CROATIAN: 'hrv',
    HUNGARIAN: 'hun',
    ARMENIAN: 'hye',
    ITALIAN: 'ita',
    JAPANESE: 'jpn',
    KANNADA: 'kan',
    KOREAN: 'kor',
    LATIN: 'lat',
    LATVIAN: 'lav',
    LITHUANIAN: 'lit',
    LUXEMBOURGISH: 'ltz',
    MACEDONIAN: 'mkd',
    DUTCH: 'nld',
    NORWEGIAN: 'nor',
    POLISH: 'pol',
    PORTUGUESE: 'por',
    ROMANIAN: 'ron',
    RUSSIAN: 'rus',
    SLOVAK: 'slk',
    SLOVENIAN: 'slv',
    SPANISH: 'spa',
    ALBANIAN: 'sqi',
    SERBIAN: 'srp',
    SWAHILI: 'swa',
    SWEDISH: 'swe',
    THAI: 'tha',
    TURKISH: 'tur',
    UKRAINIAN: 'ukr',
    VIETNAMESE: 'vie'
}
export const CONTRAST = 0.25
export const DEFAULT_FUZZY_OPTIONS = {
    distance: 100,
    isCaseSensitive: false,
    findAllMatches: false,
    location: 0,
    minMatchCharLength: 2,
    threshold: 0.6,
}
