export const CONFIG_HELPER_INTRO = `
=================================
🤖 WDIO Visual Reporter Wizard 🧙
=================================

This utility will help you generate a visual report for your WebdriverIO Visual Tests. To make use of this utility, you need to have the 'output.json' file generated by the Visual Testing service. This file is only generated when you have the following in your configuration:

export const config = {
    // ...
    services: [
        [
            // Also installed as a dependency
            "visual-regression", 
            {
                createJsonReportFiles: true,
            },
        ],
    ],
    },
}

For more information, please refer to the WebdriverIO Visual Testing documentation: https://webdriver.io/docs/visual-testing.

The goal of this utility is to help you generate a visual report by helping you

1. find the 'output.json' file
2. provide the location where you want the visual report to be created
3. generate the visual report
4. view the visual report by starting a local server
`
